In [ ]:
from feature_extraction import extract_all_features

In [ ]:
!pip install numpy joblib

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# !pip install pandas
import pandas as pd

In [ ]:
import os
print(os.getcwd())

d:\1.1_INternship


In [ ]:
url = "https://raw.githubusercontent.com/GregaVrbancic/Phishing-Dataset/master/dataset_full.csv"

df = pd.read_csv(url)

In [ ]:
df.head()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0


In [ ]:
df["phishing"].value_counts()

phishing
0    58000
1    30647
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB


In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
x = df.drop("phishing", axis=1)
y = df["phishing"]

In [ ]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (88647, 111)
y shape: (88647,)


In [ ]:
# !pip install scikit-learn
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(70917, 111)
(17730, 111)
(70917,)
(17730,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, y_train)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [ ]:
y_pred = rf.predict(x_test)
print(y_pred[:10])

[0 0 0 0 0 0 0 1 0 0]


In [ ]:
print(y_test[:10].values)


[0 0 0 0 0 0 0 1 0 0]


In [ ]:
# ACCURACY
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy", accuracy*100,"%")

Accuracy 96.9825155104343 %


In [ ]:
#CONFUSION MATRIX
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[11315   297]
 [  238  5880]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98     11612
           1       0.95      0.96      0.96      6118

    accuracy                           0.97     17730
   macro avg       0.97      0.97      0.97     17730
weighted avg       0.97      0.97      0.97     17730



In [ ]:
import joblib
joblib.dump(rf,"phishing_rf_model.pkl")

['phishing_rf_model.pkl']

In [ ]:
#only works if you are working in colab
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import joblib

joblib.dump(
    rf,
    "/content/drive/MyDrive/Phishing_rf_model.pkl"
)

['/content/drive/MyDrive/Phishing_rf_model.pkl']

In [ ]:
#shows all Features
# for i, col in enumerate(df.columns):
#     print(i, col)

0 qty_dot_url
1 qty_hyphen_url
2 qty_underline_url
3 qty_slash_url
4 qty_questionmark_url
5 qty_equal_url
6 qty_at_url
7 qty_and_url
8 qty_exclamation_url
9 qty_space_url
10 qty_tilde_url
11 qty_comma_url
12 qty_plus_url
13 qty_asterisk_url
14 qty_hashtag_url
15 qty_dollar_url
16 qty_percent_url
17 qty_tld_url
18 length_url
19 qty_dot_domain
20 qty_hyphen_domain
21 qty_underline_domain
22 qty_slash_domain
23 qty_questionmark_domain
24 qty_equal_domain
25 qty_at_domain
26 qty_and_domain
27 qty_exclamation_domain
28 qty_space_domain
29 qty_tilde_domain
30 qty_comma_domain
31 qty_plus_domain
32 qty_asterisk_domain
33 qty_hashtag_domain
34 qty_dollar_domain
35 qty_percent_domain
36 qty_vowels_domain
37 domain_length
38 domain_in_ip
39 server_client_domain
40 qty_dot_directory
41 qty_hyphen_directory
42 qty_underline_directory
43 qty_slash_directory
44 qty_questionmark_directory
45 qty_equal_directory
46 qty_at_directory
47 qty_and_directory
48 qty_exclamation_directory
49 qty_space_directo

In [ ]:
import feature_extraction

print(feature_extraction.__file__)

d:\1.1_INternship\feature_extraction.py


In [ ]:
features = extract_all_features(
    "https://google.com"
)

print(len(features))

111


In [ ]:
# Create DataFrame
features_df = pd.DataFrame([features])

print(features_df.shape)

(1, 111)


In [ ]:
#Arrange column in same order as Dataframe
features_df = features_df[
    rf.feature_names_in_
]

In [ ]:
#now predict
prediction = rf.predict(features_df)

if prediction[0] == 1:
    print("Phishing Website")
else:
    print("Legitimate Website")

Phishing Website


In [ ]:

def check_website(url):

    features = extract_all_features(url)

    features_df = pd.DataFrame([features])

    features_df = features_df[
        rf.feature_names_in_
    ]

    prediction = rf.predict(features_df)

    if prediction[0] == 1:
        print("Phishing Website")
    else:
        print("Legitimate Website")

In [ ]:
check_website("https://google.com")
check_website("https://facebook.com")
check_website("https://github.com")

In [4]:
import os
print(os.listdir('/content'))

['.config', 'sample_data']
