In [1]:
from feature_extraction import extract_all_features

In [9]:
!pip install pandas
import pandas as pd


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 4.2 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.9 MB 4.8 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/9.9 MB 5.0 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 4.7 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.2 MB/s  0:00:02


In [7]:
import os
print(os.getcwd())

d:\1.1_INternship


In [ ]:
url = "https://raw.githubusercontent.com/GregaVrbancic/Phishing-Dataset/master/dataset_full.csv"

df = pd.read_csv(url)

In [ ]:
df.head()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0


In [ ]:
df["phishing"].value_counts()

,count
phishing,
0,58000
1,30647


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB


In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
x = df.drop("phishing", axis=1)
y = df["phishing"]

In [ ]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (88647, 111)
y shape: (88647,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(70917, 111)
(17730, 111)
(70917,)
(17730,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = rf.predict(x_test)
print(y_pred[:10])

[0 0 0 0 0 0 0 1 0 0]


In [ ]:
print(y_test[:10].values)


[0 0 0 0 0 0 0 1 0 0]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy", accuracy*100,"%")

Accuracy 96.9825155104343 %


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[11315   297]
 [  238  5880]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98     11612
           1       0.95      0.96      0.96      6118

    accuracy                           0.97     17730
   macro avg       0.97      0.97      0.97     17730
weighted avg       0.97      0.97      0.97     17730



In [ ]:
import joblib
joblib.dump(rf,"phishing_rf_model.pkl")

['phishing_rf_model.pkl']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: 

In [ ]:
import joblib

joblib.dump(
    rf,
    "/content/drive/MyDrive/Phishing_rf_model.pkl"
)

['/content/drive/MyDrive/Phishing_rf_model.pkl']

In [ ]:
for i, col in enumerate(df.columns):
    print(i, col)

0 qty_dot_url
1 qty_hyphen_url
2 qty_underline_url
3 qty_slash_url
4 qty_questionmark_url
5 qty_equal_url
6 qty_at_url
7 qty_and_url
8 qty_exclamation_url
9 qty_space_url
10 qty_tilde_url
11 qty_comma_url
12 qty_plus_url
13 qty_asterisk_url
14 qty_hashtag_url
15 qty_dollar_url
16 qty_percent_url
17 qty_tld_url
18 length_url
19 qty_dot_domain
20 qty_hyphen_domain
21 qty_underline_domain
22 qty_slash_domain
23 qty_questionmark_domain
24 qty_equal_domain
25 qty_at_domain
26 qty_and_domain
27 qty_exclamation_domain
28 qty_space_domain
29 qty_tilde_domain
30 qty_comma_domain
31 qty_plus_domain
32 qty_asterisk_domain
33 qty_hashtag_domain
34 qty_dollar_domain
35 qty_percent_domain
36 qty_vowels_domain
37 domain_length
38 domain_in_ip
39 server_client_domain
40 qty_dot_directory
41 qty_hyphen_directory
42 qty_underline_directory
43 qty_slash_directory
44 qty_questionmark_directory
45 qty_equal_directory
46 qty_at_directory
47 qty_and_directory
48 qty_exclamation_directory
49 qty_space_directo

In [3]:
url = "https://google.com"

features = extract_all_features(url)

print(len(features))

105


In [10]:
url = "https://google.com"

features = extract_all_features(url)

features_df = pd.DataFrame([features])

print(features_df.shape)

(1, 105)
